name = "fetch_callbacks"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "Make HTTP requests in Gleam JavaScript with Fetch, but with callbacks"
target = "javascript"
gleam = ">= 0.32.0"

# fix this toml later !!!

repository = { type = "github", user = "Vakiyama", repo = "fetch" }
links = [
  { title = "Website", href = "https://gleam.run" },
]

[dependencies]
gleam_http = "~> 3.1"
gleam_javascript = "~> 0.3 or ~> 1.0"
gleam_stdlib = "~> 0.32 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
